import pandas as pd 
import numpy as np

datos = pd.read_csv("matches_serie_A.csv", encoding="latin-1")
df = pd.DataFrame(datos)    
print(df)
print("\n"*1)
print("cuantos goles anoto el inter de milan en la temporada 2025:")
print(df[(df['Team'] == 'Internazionale') & (df['Season'] == 2025)]['GF'].sum())
print("\n"*1)
print("cuantos goles anoto el AC milan en la temporada 2025:")
print(df[(df['Team'] == 'Milan') & (df['Season'] == 2025)]['GF'].sum())
print("\n"*1)
print("cuantos goles recibio el inter en la temporada 2025:")
print(df[(df['Team'] == 'Internazionale') & (df['Season'] == 2025)]['GA'].sum())
print("\n"*1)
print("cuantos goles recibio el AC milan en la temporada 2025:")
print(df[(df['Team'] == 'Milan') & (df['Season'] == 2025)]['GA'].sum())
print("\n"*1)
print("cuantas victorias de visitante tiene el inter en la temporada 2025:")
print(df[(df['Team'] == 'Internazionale') & (df['Venue'] == 'Away') & (df['Result'] == 'W') & (df['Season'] == 2025)].shape[0])
print("cuantas victorias tiene de visitante el AC milan")
print(df[(df['Team'] == 'Milan') & (df['Venue'] == 'Away') & (df['Result'] == 'W') & (df['Season'] == 2025)].shape[0])
print("Inter porterias a cero en la temporada 2025:")
print(df[(df['Team'] == 'Internazionale') & (df['GA'] == 0) & (df['Season'] == 2025)].shape[0])
print("AC milan porterias a cero en la temporada 2025:")
print(df[(df['Team'] == 'Milan') & (df['GA'] == 0) & (df['Season'] == 2025)].shape[0])
print("cuanta posicion tuvo el inter en la temporada 2025:")
print(df[(df['Team'] == 'Internazionale') & (df['Season'] == 2025)]['Poss'].sum())
print("cuanta posicion tuvo el AC milan en la temporada 2025:")
print(df[(df['Team'] == 'Milan') & (df['Season'] == 2025)]['Poss'].sum())